### ISSUE TITLE
version 1.5.0 cannot create an new account and stays locked

### ISSUE THREAD

**Issue by ZeHiro** [y-lohse/cozy-thelounge#2]
I get this in the logs: 

```
[thelounge] Enter password:

```

When I try to launch the application manually (npm start in the directory), with cli, the above console statement stays. When looking at the code of the original app, it appears the lounge.add command does not accept a password anymore...

**Comment by clochix** [comment]
I can confirm that new users are unable to install latest version of the application :-S

**Comment by ZeHiro** [comment]
Fixed
