### ISSUE TITLE
Random http vs. https request

### ISSUE THREAD

**Issue by notabene** [y-lohse/cozy-thelounge#3]
Hi,

I'm using The Lounge and periodically Firefox says it cannot request an element. Then it asks for a reload and then the page works.

From what I gather:
1. Some NTLM authentication is failing (I'm behind an enterprise proxy). I get a 407 (Proxy authentication required).
   ![NTLM failing](https://cloud.githubusercontent.com/assets/664145/16804789/bf86411c-490d-11e6-8865-c35524de4256.png)
2. Seemingly at this point requests go through http and not https after this point.
   ![HTTP security shown](https://cloud.githubusercontent.com/assets/664145/16804788/bf8450d2-490d-11e6-8631-c286733484d0.png)

Do you think at some point The Lounge jumps from https to http on its own or is it unsolvable as it is a proxy bug?

**Comment by ZeHiro** [comment]
I think it is a proxy or laverna problem, not the port to cozy.

**Comment by notabene** [comment]
@ZeHiro Do you know where I should report it then?

**Comment by y-lohse** [comment]
Hi,
You can probably report it directly to cozy, though I'm not sure where the problem comes from. I don't _think_ that the lounge would change protocol on it's own, but I have no idea. And even if it does, it's more of an upstream bug than a bug within this port :|

**Comment by notabene** [comment]
Thanks @y-lohse I'll report to the Cozy team directly.

**Comment by y-lohse** [comment]
No problem. If it turns out it's actually a problem specific to the lounge, don't hesitate to re-open this issue and we can take a look at it before reporting it upstream.
